package dk.creditoro.client.core;

public enum EventNames {
    LOGIN_RESULT,
    ON_SEARCH_CHANNELS_RESULT,
    ON_SEARCH_PRODUCTIONS_RESULT,
    ON_SEARCH_PEOPLE_RESULT,
    ON_SEARCH_CREDITS_RESULT,
    ON_PATCH_CREDITS_RESULT,
    ON_POST_CREDITS_RESULT,
    ON_POST_PERSON_RESULT
}
